### ISSUE TITLE
problem with cooking

### ISSUE THREAD

**Issue by Coreycore420** [InfernoDragon0/CotLMods#9]
I tried to cue up some meals for my followers (I think I clicked more than 15 times) on the max upgraded cooking station, the window closed and I was unable to interact with the cooking station, non of my cook followers would go cook the meals I made and when I went to reload the cooking menu briefly opened only to close again (the prompt for cook came up when I tried again and the same thing happened) I uninstalled the mod to try and feed my followers and my entire base was scrambled (including immovable objects, and some where out of bounds) I can't find a work around to feed my cult. 
hope this helps bug busting have a wonderful day.

**Comment by InfernoDragon0** [comment]
Hi, will you be able to provide a little more information about this?

To workaround the 15 meals limit you will have to interact with a follower and ask them to work as chefs, or, you will have to wait until they are interested in cooking and they will start cooking on the cooking station. This is due to a hardcoded array in the base game itself, not allowing you to interact with the cooking station if you have more than 15 items queued up in it.

Uninistalling mods is currently not supported yet, so you will have to reinstall the mod to fix the save file.

Note that latest versions are usually on Thunderstore, and 3-4 days later will appear on NexusMods

- LogOutput.txt from Bepinex folder
- Base Game version
- COTL API version
- CotL Mini Mods version

Thanks for reporting :)

**Comment by Coreycore420** [comment]
sorry for such a late reply (School been killing me) I didnt save and added the mods back in and my file was fine :), I looked at the game again and it looks like there are meals fully cued but no matter how long I wait non of the follower (even ones I had assigned before and after the glitch) would go to cook, the cults food meter was very hungry but not quite starving yet, hope this helps :)

**Comment by InfernoDragon0** [comment]
I see, sorry for the late reply as well. The implementation for that part of the mod will have a major change next patch which will also remove this problem. Thanks!
